### ISSUE TITLE
Unhandled Exception while disposing ExtFileStream

### ISSUE THREAD

**Issue by christopher-fabian** [nickdu088/SharpExt4#10]
Hi,

I get an unhandled exception during disposing the ExtFileStream.
The target framework of my application is .NET 7.

I do simple copy operations of large files (up to 2 GB) from my NTFS-Disk to a Micro-SD (Ext4).

Source
```

  ExtDisk disk = ExtDisk.Open(diskNumber);
  ExtFileSystem fileSystem = ExtFileSystem.Open(disk, disk.Partitions[0]);

  byte[] buffer = File.ReadAllBytes(sourcePath);

  using ExtFileStream stream = fileSystem.OpenFile(destinationPath, FileMode.Create, FileAccess.Write);
  stream.Write(buffer, 0, buffer.Length);
  stream.Close();
```

The operation is successful but after the call of Dispose via the using-operator or calling Dispose I get the following exception:
![grafik](https://user-images.githubusercontent.com/12455803/207066300-60239626-09f3-481d-a0b6-29c2810a6f36.png)
![grafik](https://user-images.githubusercontent.com/12455803/207066359-93b19b75-5749-487b-9dff-df22bde4bfa2.png)
![grafik](https://user-images.githubusercontent.com/12455803/207066890-60ec8a13-6e17-4bb7-b0e1-f7807de8e695.png)

Is this the default behavior? 
Any idea for a workaround?

~Best Regards

**Comment by nickdu088** [comment]
Compile as release mode and try again.

**Comment by christopher-fabian** [comment]
Same result in release mode:

![grafik](https://user-images.githubusercontent.com/12455803/207414791-13fa7cdd-aa82-4324-a00b-b16d2d01797f.png)

**Comment by nickdu088** [comment]
Then it could be heap corruption.

**Comment by christopher-fabian** [comment]
Do you have any idea how to check if the heap is corrupted and/or how to fix it? I‘m not familar with problems like this.

**Comment by nickdu088** [comment]
Just a quick glimpse the screen shot you attached, it seems you are using x64 release, as you can see ext4_write takes uint64 as input, however extfilestream passes int32. 

You said you were copying large file (2gb). This may be the reason.

Try x86 mode, or use smaller file

**Comment by christopher-fabian** [comment]
Thank you for your tips.

I found out the error only occurs when ExtFileStream.Close() is called shortly before disposing.

If I skip closing the stream before disposing, it works.
But on the other hand I get a memory leak, the RAM is not released properly.

Is disposing not closing the stream at all? I think this would be the expected behavior.

Maybe we can improve the whole thing, Dispose should better not throw an error exception if the stream is closed.

**Comment by nickdu088** [comment]
ExtFileStream inherits . Net Stream class and override close.
https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtFileStream.h#L37

It should be all handled by Stream base class.
