### ISSUE TITLE
Could not read disk MBR error

### ISSUE THREAD

**Issue by Keops10** [nickdu088/SharpExt4#11]
Hello
I mount a Linux-based virtual machine (vhdx) with the arsenal mounter. I see this added in Disk management I want to access this disk with Sharpext4 and read and copy it I couldn't find how to do it. I used the code below but I get the Could not read disk MBR error.
  
private void Mountet_Click(object sender, RoutedEventArgs e)
        {
            //Open a Linux ext4 disk image
            var disk = ExtDisk.Open(1);
            //Get the Linux partition, and open
            var fs = ExtFileSystem.Open(disk, disk.Partitions[0]);
            //List all files in /etc folder
            foreach (var file in fs.GetFiles("/etc", "*", SearchOption.AllDirectories))
            {
                Console.WriteLine(file);
            }
        }        }

**Comment by nickdu088** [comment]
You need to convert the virtual machine (.vhdx) format to the raw disk format.

**Comment by Keops10** [comment]
Can you give an idea on how I can do this?

**Comment by nickdu088** [comment]
https://social.technet.microsoft.com/Forums/en-US/bea9fc55-b7df-42ba-9a38-362ef51e9b74/how-to-convert-vhdx-file-to-raw?forum=winservergen

https://docs.openstack.org/image-guide/convert-images.html

As far as I know, the file header format is different.

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-vhdx/f0efbb98-f555-4efc-8374-4e77945ad422

**Comment by Keops10** [comment]
Yep, it doesn't seem to work for me. Actually, I can read the paths of the files with DiscUtils, but I need to export these files. Any idea how it could be?

**Comment by nickdu088** [comment]
If you can use diskutils, you should be able export those files without any issue. Diskutils only provides read permission only from the disk image, but not write.

SharpExt4 allows you to write a file to the disk image.

**Comment by Keops10** [comment]
I am reading with this code. If I make any changes to this code, I can export it.


```
 var disk = new DiscUtils.Vhdx.Disk(secilen.Text, System.IO.FileAccess.Read);
                    DiscUtils.FileSystems.SetupHelper.SetupFileSystems();
                    var manager = new VolumeManager(disk);
                    var logicalVolumes = manager.GetLogicalVolumes();
                    foreach (var volume in logicalVolumes)
                    {
                        var fsInfos = FileSystemManager.DetectFileSystems(volume);

                        foreach (var fsInfo in fsInfos)
                        {
                            var fs = fsInfo.Open(volume);

                            string[] array2 = fs.GetFiles(fs.Root.Name, "*.*", SearchOption.AllDirectories);
                            foreach (string name in array2)
                            {
                                listbox.Items.Add(name);
                            }
                        }
                    }
```

**Comment by nickdu088** [comment]
listbox.Items.Add(name)
//Open file and read the content from the name
...

**Comment by Keops10** [comment]
I don't think it's possible with something like this, but I tried it anyway.



```
string dd = listbox.SelectedItem.ToString();
FileStream fs = File.Open(dd,FileMode.Open);
```

**Comment by nickdu088** [comment]
You can't just use File.Open(dd,FileMode.Open). That is the.net native way. You need use diskutils API to open the file. Check diskutils file open API.
