### ISSUE TITLE
Could not mount partition error when read Flash Usb Ext4

### ISSUE THREAD

**Issue by thuongthinh** [nickdu088/SharpExt4#12]
Hello!
I use this library to read data in Usb Ext4 but get an error "Could not mount partition" at the line: var fs = ExtFileSystem.Open(disk, disk.Partitions[0]);
Please help me! Thanks!

**Comment by thuongthinh** [comment]
I have run application in admin permission

**Comment by nickdu088** [comment]
Please follow https://www.nickdu.com/?p=890
