### ISSUE TITLE
(It can be simply modified to be compiled in Visual Studio 2013). How?

### ISSUE THREAD

**Issue by thuongthinh** [nickdu088/SharpExt4#14]
Hello!
I compiled using visual studio 2013 with .NET 3.5 and got error LNK2001 and LNK2019 in lwext4.lib

(It can be simply modified to be compiled in Visual Studio 2013). How?
Thanks!

**Comment by nickdu088** [comment]
What error did you get?
I can't remember exactly what I did last time, but it's quite simple to modify (one line code change).

**Comment by thuongthinh** [comment]
I build SharpExt4 with .net 3.5 and got error:  Tuple is not template. Tuple only available in .net4.0 and above.
![image](https://user-images.githubusercontent.com/20676183/209694852-84ce95c2-d798-4abe-9f0a-f3d10b8117ac.png)

**Comment by nickdu088** [comment]
https://stackoverflow.com/questions/7120845/equivalent-of-tuple-net-4-for-net-framework-3-5

**Comment by thuongthinh** [comment]
Thanks!
