### ISSUE TITLE
Error: Could not load file or assembly 'SharpExt4.dll' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by thuongthinh** [nickdu088/SharpExt4#15]
Hello!
I compiled the sample code SharpExt4-main on .net 4.5, I run on my computer it works fine. When I copy file .exe and .dll to another computer, I get the above error:  "Could not load file or assembly 'SharpExt4.dll' or one of its dependencies. The specified module could not be found".
Help me!

**Comment by thuongthinh** [comment]
SharpExt4.dll build Win32
Sample.exe: Build x86
Run on Win7 32 bit

**Comment by nickdu088** [comment]
Once SharpExt4 project is compiled, it will generate SharpExt4.dll in the release/debug folder depending on your settings.

**Comment by thuongthinh** [comment]
I compiled the sample code SharpExt4-main. Deploy on another computer without visual studio installed.
![image](https://user-images.githubusercontent.com/20676183/209952472-ea17cd07-5047-428e-ab36-f1b7759912ff.png)

**Comment by nickdu088** [comment]
first you need compile the project as release version as new computer doesn't have debug environment.
2nd, new computer must have .net installed or even vc++ redistribution (vs2013) installed.
https://www.microsoft.com/en-nz/download/details.aspx?id=40779
https://www.microsoft.com/en-au/download/details.aspx?id=40784

**Comment by thuongthinh** [comment]
Thanks!
