### ISSUE TITLE
Unable to recognize EXT4 extended partition

### ISSUE THREAD

**Issue by jeff60301** [nickdu088/SharpExt4#18]
Could you add the read and write function of the extended partition to SharpExt4?

**Comment by nickdu088** [comment]
I think it supports extended partition?

**Comment by jeff60301** [comment]
![4](https://github.com/nickdu088/SharpExt4/assets/96248880/d18957e6-417c-4b66-b690-bb89d798e70b)
![5](https://github.com/nickdu088/SharpExt4/assets/96248880/cd3c1c00-4679-439a-881c-e44b8b8a9fc9)

How to read and write the extended partition of 4-11?

**Comment by nickdu088** [comment]
This could be the limitation of lwext4.
https://github.com/nickdu088/SharpExt4/blob/main/lwext4/src/ext4_mbr.c#L104

**Comment by nickdu088** [comment]
If you know the extended partition offset of 4-11, you can manually add those partitions and test.

**Comment by jeff60301** [comment]
> If you know the extended partition offset of 4-11, you can manually add those partitions and test.

Sorry, I'm not professional about this.

**Comment by jeff60301** [comment]
> If you know the extended partition offset of 4-11, you can manually add those partitions and test.

Could you add it?

**Comment by nickdu088** [comment]
> > If you know the extended partition offset of 4-11, you can manually add those partitions and test.
> 
> Could you add it?

see here:
https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtDisk.cpp#L67C1-L73C5

You can add any partition you like.

It only needs offset and size.
https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtFileSystem.cpp#L208

**Comment by ph9990420** [comment]
When I increase the size of struct ext4_part_entry part_entry, why do I only see the type of the primary partition and the extended partition, and completely fail to find the type of logical partitions under the extended partition?
![disk](https://github.com/nickdu088/SharpExt4/assets/157883096/f58550ec-8fce-45fe-a0cf-73a32a7230fa)

**Comment by nickdu088** [comment]
> When I increase the size of struct ext4_part_entry part_entry, why do I only see the type of the primary partition and the extended partition, and completely fail to find the type of logical partitions under the extended partition? ![disk](https://private-user-images.githubusercontent.com/157883096/300170855-f58550ec-8fce-45fe-a0cf-73a32a7230fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTAzMDAsIm5iZiI6MTcwNjM1MDAwMCwicGF0aCI6Ii8xNTc4ODMwOTYvMzAwMTcwODU1LWY1ODU1MGVjLThmY2UtNDVmZS1hMGNmLTczYTMyYTcyMzBmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMDA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGY2YjZkOTRmYWUwN2MwY2E4NDlhNzFiMmI1MzEyOGUzNTgxNDBlNWU4Nzg5MjIwNDQyNjQwZWIyNDQ0ZmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1O2dxAK5VFQV1YbxQ7swe5Xi13GmI8D_pX5ozIl1MBM)

For lwext4 limitation, you'd better ask lwext4 auther to update the library.

What I am asking you is to add more partitions in ExtDisk.cpp (ignoring the lwext4 returns):
https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtDisk.cpp#L67C1-L73C5
But you should know the partition size and offset.
