### ISSUE TITLE
Update Docs and cannot mount ext4 partition

### ISSUE THREAD

**Issue by john-nv** [nickdu088/SharpExt4#19]
This library is great, but can you update the docs, it's very difficult to learn and use,
Thank u

**Comment by nickdu088** [comment]
This is the sample how to use the library step by step: https://www.nickdu.com/?p=890

**Comment by john-nv** [comment]
![z5361154663706_b8d69ba2fdf0bbe41782d97f83b474a9](https://github.com/nickdu088/SharpExt4/assets/53093032/83da8b25-bad7-46d7-91f5-a5239edae073)

I downloaded your library and added the SharpExt4.dll file from the debug folder to the reference to use.
I was able to read the disk, but couldn't access the fartition, but checked the log and it existed
I use `ExtFileSystem.Open(disk, partition);`
but it has a new update from you, but I can't use it

**Comment by john-nv** [comment]
I just need to build SharpExt4 x86 and use 1 SharpExt4.dll file for reference, right? I use C#, I'm not an expert in C, please help me, running C# project x86
Thank you

**Comment by john-nv** [comment]
I ran VSstudio as administrator according to the instructions but still cannot access the partition
Below are some of my parameters
It is form USB `MBR ext4 linux`
![2](https://github.com/nickdu088/SharpExt4/assets/53093032/3e358f73-13b1-47c0-b4c5-a2753db42cb3)

**Comment by nickdu088** [comment]
This is the sample code you can follow.
https://github.com/nickdu088/SharpExt4/blob/main/Sample/Program.cs

**Comment by nickdu088** [comment]
> I ran VSstudio as administrator according to the instructions but still cannot access the partition Below are some of my parameters It is form USB `MBR ext4 linux` ![2](https://private-user-images.githubusercontent.com/53093032/323714555-3e358f73-13b1-47c0-b4c5-a2753db42cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Nzk1NjQsIm5iZiI6MTcxMzQ3OTI2NCwicGF0aCI6Ii81MzA5MzAzMi8zMjM3MTQ1NTUtM2UzNThmNzMtMTNiMS00N2MwLWI0YzUtYTI3NTNkYjQyY2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZTYwYmMyZjg4YWY2Yzc0Zjg0MmJlNDdjNDgyMTFjYWI1YmY3ZTIxOGJhYjZlYTUwM2I4MTNjZmNmOTczZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.blC3wqZi6cmh0176LNkpGda3TM-Q5A5ViGWjBAC132o)

In disk 3, which partition is ext4 partition?
This library can only process Linux EXT2, EXT3, EXT4 partition.

**Comment by john-nv** [comment]
Yes, That disk is etx4

**Comment by nickdu088** [comment]
> Yes, That disk is etx4

how many partitions in that disk, what are those partitions. **This library can only process Linux EXT2, EXT3, EXT4 partition.**

**Comment by john-nv** [comment]
I just checked again, it's silly because I selected the wrong drive...., Let me ask more, do you have a method to display all available drives, or a method to display the capacity of that disk?

**Comment by nickdu088** [comment]
> I just checked again, it's silly because I selected the wrong drive...., Let me ask more, do you have a method to display all available drives, or a method to display the capacity of that disk?

.Net has library to support what you ask.

**Comment by john-nv** [comment]
I will learn more, thank you, have a good day
