### ISSUE TITLE
Typo on ExtDisk "Partitions" getter

### ISSUE THREAD

**Issue by xcontra** [nickdu088/SharpExt4#2]
Hi,

I've been using this library and It's really helpful, thanks for it!

I just noticed there's a typo on the "Partitions" getter in the "ExtDisk" class.
Instead of saying `Partitions` it says `Parititions`.

Files:
- SharpExt4/SharpExt4/ExtDisk.cpp
https://github.com/nickdu088/SharpExt4/blob/36d52b6f09e3b1276d0c51a146849964069ea721/SharpExt4/ExtDisk.cpp#L155
- SharpExt4/SharpExt4/ExtDisk.h
https://github.com/nickdu088/SharpExt4/blob/36d52b6f09e3b1276d0c51a146849964069ea721/SharpExt4/ExtDisk.h#L90

**Comment by nickdu088** [comment]
> Hi,
> 
> I've been using this library and It's really helpful, thanks for it!
> 
> I just noticed there's a typo on the "Partitions" getter in the "ExtDisk" class. Instead of saying `Partitions` it says `Parititions`.
> 
> Files:
> 
> * SharpExt4/SharpExt4/ExtDisk.cpp
>   https://github.com/nickdu088/SharpExt4/blob/36d52b6f09e3b1276d0c51a146849964069ea721/SharpExt4/ExtDisk.cpp#L155
> * SharpExt4/SharpExt4/ExtDisk.h
>   https://github.com/nickdu088/SharpExt4/blob/36d52b6f09e3b1276d0c51a146849964069ea721/SharpExt4/ExtDisk.h#L90

You are right. My silly mistake. :)
Thanks!
