### ISSUE TITLE
'^': cannot use this indirection on type 'System::Collections::Generic::LinkedList'

### ISSUE THREAD

**Issue by tr1fled** [nickdu088/SharpExt4#23]
Hello, today i tried to compile this project using the release config, but i got this error message ([C3699](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3699?view=msvc-170)) on the file `ExtFileSystem.cpp` line 266:
```
'^': cannot use this indirection on type 'System::Collections::Generic::LinkedList'
```
How can I fix this issue?

**Comment by nickdu088** [comment]
I don't see any error in release config? Which release config did you use x64, x86 and which compiler did you use?

**Comment by tr1fled** [comment]
i am using x64, and a fresh install of visual studio 2022 in windows, if you need me to reinstall it or try anything else lmk

**Comment by nickdu088** [comment]
Interesting. I am using Microsoft Visual Studio Community 2022 (64-bit) - Version 17.11.2 and MSVC v143 - VS2022 C++
It all works great locally.

**Comment by 0x410c** [comment]
same issue with vs studio 2022 preview

**Comment by nickdu088** [comment]
try the latest update and see if it solves the issue.

**Comment by 0x410c** [comment]
same issue

**Comment by nickdu088** [comment]
check this: https://github.com/nickdu088/SharpExt4/actions/runs/10861469463/job/30143399248
It builds successfully.

**Comment by 0x410c** [comment]
working! thanks
