### ISSUE TITLE
How to read/write to ext4 partition image

### ISSUE THREAD

**Issue by znoble360** [nickdu088/SharpExt4#25]
I have an ext4 partition image that I need to read and write to so that I can modify files before flashing the partition to a device as it's rootfs partition. This way I can flash the rootfs with certain settings already set and not have to go in and customize it after the fact. As far as I can tell the ext4 file that I'm trying to modify should be a raw partition, and from what I was reading it sounds like reading and writing to a raw partition file isn't directly supported right now.

I was trying to read through issues #3 and #24 , and it seems like they're trying to do something similar to what I want to do, but I wasn't able to figure out how to do it from what was in those 2 issues

I tried opening the ext4 file like so: `rootfsDisk = ExtDisk.Open(@".\rootfs.ext4");`, but i'm just getting an error about not being able to read mbr disk

**Comment by nickdu088** [comment]
Definitely you can read/write a ext4 partition directly. Like #24 said you have to construct the fake partition to pass in. 

Follow the instructions in #24

**Comment by znoble360** [comment]
well I tried what was in #24  but like I said, when I tried to run the `ExtDisk.Open(@".\rootfs.ext4");` function to open the ext4 file, it complains about not being able to open the MBR disk, which makes sense to me since the rootfs.ext4 file doesn't have the disk info in it, it's just a partition and not a disk. So then do I need to pass something else to the ExtDisk.Open function? that's the part I wasn't sure what to pass instead.

**Comment by nickdu088** [comment]
You can return the disk at: https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtDisk.cpp#L58 to bypass MBR checking.

**Comment by znoble360** [comment]
Would it matter that my partition image also is also a sparse image? I bypassed the mbr check and now the filesystem open is telling me "could not mount partition"

**Comment by nickdu088** [comment]
I guess so. Can you convert your sparse image to a raw image?

**Comment by znoble360** [comment]
I thought it was sparse but apparently it's not. Then I'm still not sure what the deal is

**Comment by znoble360** [comment]
Well technically it might be sparse - when I flash it to a real drive, it takes up the same space on the drive as the file image's size, but the partition can be bigger - I think that just has to do with the partition table though. Like for example: my partition image file takes up 1.2G, and when I do `cp --sparse=never old.ext4 new.ext4` it still takes up the same space. But when I mount it in linux it says the loopback device is 1.4G big, with 1.2G used.

But I know I can mount the partition in linux and I can view it with a program like "ext2explorer" on windows so it should be a good partition image

**Comment by znoble360** [comment]
Ok, I figured out my problem. It was an issue with the filesystem features not being supported by lwext4, so not an issue with this library. Everything you said worked once I removed the unsupported ext4 features from the partition

**Comment by nickdu088** [comment]
> Ok, I figured out my problem. It was an issue with the filesystem features not being supported by lwext4, so not an issue with this library. Everything you said worked once I removed the unsupported ext4 features from the partition

Good to know that. Thanks for sharing your experience.
