### ISSUE TITLE
Open partition from a file system image?

### ISSUE THREAD

**Issue by pnill** [nickdu088/SharpExt4#3]
Is there an easy way to currently open a partition from an image of the partition itself vs a full disk image? I don't see any easy way to do that with the sample provided/library code.

So far, I kinda 'hacked' in a partition to fake disk by just populating the partitions array and that worked to read/write from the partition image on disk basically tricking things into thinking it was a disk image, but the resulting image is damaged once a file is written and has to be repaired.

Just wondering if this use case has ever been considered or if there's a known easy way to approach it?

This is what I'd done so far to 'hack' my partition in as the 'disk':
```
SharpExt4::ExtDisk^ SharpExt4::ExtDisk::Open(String^ imagePath)
{
	if (File::Exists(imagePath))
	{
		auto disk = gcnew ExtDisk(imagePath);
		disk->bdevs = new ext4_mbr_bdevs();
		disk->capacity = 786432000;
		disk->geometry = gcnew SharpExt4::Geometry(0, 0, 0, 0);
		disk->partitions = gcnew List<Partition^>();

		Partition^ partition = gcnew Partition();
		partition->Offset = 0;
		partition->Size = 786432000;
		disk->partitions->Add(partition);

		return disk;

```

Which worked to list, create, and get contents of files; but again upon saving it seems to damage the partition image maybe because it's trying to update data in relation to a disk not sure, what it does is fixable via e2fsck but I'm wanting to avoid having to use that every time I modify the image.

**Comment by nickdu088** [comment]
I didn't see any user case for that. Partition itself can not survive alone without disk (container), therefore you must open a disk first before opening a partition. 

From your 'hacked' code, if you do know the partition offset, you can manually open it without issue. 
But from a library point of view, I want to give a unified way to operate e.g. disk->partition->file...

If you still want to 'hack' the code, you may need to take a look this
https://github.com/nickdu088/SharpExt4/blob/43b0f383eff44bab00ff9279433735b3f96235ea/SharpExt4/ExtDisk.cpp#L100

**Comment by ivanjx** [comment]
or you can write a new function for your needs yourself. at least this is what i need to delete a file from a raw ext4 partition (not disk):
```
	char* part_path = (char*)Marshal::StringToHGlobalAnsi(part_path_str).ToPointer();
	ext4_io_raw_filename(part_path);
	struct ext4_blockdev* bd = ext4_io_raw_dev_get();

	int register_result = ext4_device_register(bd, "partition1");
	int mount_result = ext4_mount("partition1", "/partition1/", false);
	int journal_result = ext4_journal_start("/partition1/");
	int cache_result = ext4_cache_write_back("/partition1/", false);
	int delete_result = ext4_fremove("/partition1/path/to/file");
```
