### ISSUE TITLE
GPT partition

### ISSUE THREAD

**Issue by wisper-sabrina** [nickdu088/SharpExt4#8]
Hello,

I want to mount a ext4 partition GPT, is it possible ?

Regards.

**Comment by nickdu088** [comment]
No. Currently it only supports MBR.

**Comment by wisper-sabrina** [comment]
would it be possible to mount an ext4.img image on an ext4 gpt partition ?

**Comment by nickdu088** [comment]
> would it be possible to mount an ext4.img image on an ext4 gpt partition ?

Internally, it all goes through the same function call. 
Once GPT disk supports, GPT image will automatically be supported.

**Comment by wisper-sabrina** [comment]
do you plan to implement it soon ?

Thanks for your answers.

**Comment by nickdu088** [comment]
No. I am busy with my own work.
Can someone from the community implement GPT support?

**Comment by kuttikrishnan** [comment]
@nickdu088 ,

Thanks for your help and support which you provided in the past .

Please let me know if there are any way I can read from a GPT partition. Currently I am able to read from a MBR partition. Now I have a SSD which have GPT partition.

It will be great if you are able to help me on this.

Thanks and Regards,
Kutti

**Comment by nickdu088** [comment]
From wiki: https://en.wikipedia.org/wiki/GUID_Partition_Table
It shouldn't hard to work on GPT but to jump to the EXT4 partition. You can take a look this: https://github.com/nickdu088/SharpExt4/blob/main/SharpExt4/ExtDisk.cpp#L59

I don't have time to work on GPT right now or you can extend GPT support?

**Comment by kuttikrishnan** [comment]
Hi @nickdu088 ,

Thanks for your response. I am not an expertise in C/C++. I normally work with Microsoft Technology stack (C#,Dotnet Core,SQLAzure...). So, I am not sure about implementing the GPT implementation.

It will be really helpful if you have any other references or code.

Regards,
Kuttikrishnan.P

**Comment by nickdu088** [comment]
Just added GPT disk support.

**Comment by kuttikrishnan** [comment]
@nickdu088 

Thank you very much for adding GPT disk support. This is very helpful.

I have checked the [ code samples] (https://github.com/nickdu088/SharpExt4/blob/main/Sample/Program.cs) to call MBR/GPT.  How can I programmatically (through C#) determine whether to open a GPT or MBR disk based on the type of USB drive?


Regards,
@kuttikrishnan

**Comment by nickdu088** [comment]
You should know your disk type?
Otherwise try to read MBR/GPT first. If it fails, then try another one.
I haven't tried this way.
