### ISSUE TITLE
ext4 for bootmgr.efi (Windows 7, 8, 10, 11)

### ISSUE THREAD

**Issue by OLuserGi** [nickdu088/SharpExt4#9]
Hello!
I want install my Windows 11 for test into EXT4 base partition or into vDISK.vhdx, which save into EXT4 base partition.
I do this:
1) HDD 120GB = 2 GB FAT16 + 109,6 GB EXT4 base partition;
2) Save vDISK.vhdx 100 GB NTFS to 109,6 GB EXT4 base partition;
3) Save bootmgr.efi into 2 GB FAT16;
I need 4) mount EXT4 base partition (driver ext4_x64.efi) over BCD and bootmgr.efi;
5) Mount vDISK.vhdx 100 GB NTFS over BCD and bootmgr.efi;
6) Install Windows to vDISK.vhdx.

Now I have work OS Windows 11 on vDISK.vhdx into NTFS base partition. This work. I want use EXT4 base partition.

Can you help me?

**Comment by nickdu088** [comment]
Sorry. Don't understand what you are doing.
